/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.mycompany.sistema.Funcionario;
import com.mycompany.sistema.Gerente;
import com.mycompany.sistema.item;
import java.security.Permission;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author micka
 */
public class Menu extends javax.swing.JFrame {
    //SETANDO O ARRAYLIST DOS ITENS
    ArrayList<item> myData = new ArrayList<>();
    //INICIANDO TABELA DE DADOS
    DefaultTableModel tabela;
    //Object[] linhaAux = {2482,"TESTE",8,15.3};
    public void iniciarTabela() {
        tabela = (DefaultTableModel) this.tabelaDados.getModel();
    }
    
    public void inicializar() {
        //INICIALIZANDO OS ITENS
        item itemAux = new item("Carne 1Kg", 25,17525, 37.8);
        myData.add(itemAux);
        itemAux = new item("Feijão 1Kg",120,17526,14.3);
        myData.add(itemAux);
        itemAux = new item("Iogurte 500ml",28,17527,3.42);
        myData.add(itemAux);
        itemAux = new item("Achocolatado 200g",12,17528,5.19);
        myData.add(itemAux);
        iniciarTabela();
        atualizarTabela();
    }
    
    public Menu() {
        initComponents();
    }
    public int control;
    public void atualizarTabela() {
        if (control == 0) {
            //REMOVENDO ITENS ANTERIORES
        tabela.getDataVector().removeAllElements();
        tabela.fireTableDataChanged();
        //ADICIONANDO NOVOS ITENS
        for (int i = 0; i < myData.size(); i++) {
            Object[] linhaAux = new Object[]{myData.get(i).getBarras(),myData.get(i).getNome(),myData.get(i).getQuantidade(),myData.get(i).getValor()};
            tabela.addRow(linhaAux);
        }
        control++;
        }
    }
    //IMPORTA OS USUÁRIOS CRIADOS
    private Funcionario funcionario;
    private Gerente gerente;
    private int privilegio;
    //DEFINE A VARAVEL DA PERMISSÃO PARA EDITAR A TABELA
    public void eFuncionario(Funcionario f1) {
        funcionario = f1;
        //CONFIGURA O NOME DOS FUNCIONÁRIOS NOS LUGARES CERTOS.
        NomePessoa.setText(f1.getNome());
        campoAlteradorNome.setText(f1.getNome());
        //INICIALIZANDO TABELA DE DADOS
        this.inicializar();
        //LIBERA O CAMPO DE CLIENTES E O BOTÃO
        CampoCliente.setEnabled(true);
        botaocliente.setEnabled(true);
    }
    public void eGerente(Gerente g1) {
        gerente = g1;
        //HABILITA OS COMANDOS ESPECIAIS DO GERENTE
        NomePessoa.setText(g1.getNome());
        botaoAlteradorNome.setEnabled(true);
        campoAlteradorNome.setEnabled(true);
        campoAlteradorNome.setText(g1.getNome());
        //INICIALIZANDO TABELA DE DADOS
        this.inicializar();
        //EXIBINDO MENSAGEM DE PERMISSÃO
        textoEditar.setText(gerente.StaffMensage());
        textoEditar.setForeground(new java.awt.Color(0,255,0));
        tabelaDados.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomePessoa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        painel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        CodigoBarrasVender = new javax.swing.JTextField();
        CampoVenderQuantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botaovender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textoValor = new javax.swing.JLabel();
        CampoCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoEditar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        campoAlteradorNome = new javax.swing.JTextField();
        botaoAlteradorNome = new javax.swing.JButton();
        botaocliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BEM VINDO(A): ");

        NomePessoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NomePessoa.setText("NaN");

        jScrollPane2.setWheelScrollingEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("VERIFICAR");

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO DE BARRAS", "NOME", "QUANTIDADE", "PREÇO"
            }
        ));
        tabelaDados.setShowGrid(false);
        tabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaDados);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("VENDER/ACESSO RÁPIDO");

        CodigoBarrasVender.setEditable(false);
        CodigoBarrasVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoBarrasVenderActionPerformed(evt);
            }
        });

        CampoVenderQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoVenderQuantidadeActionPerformed(evt);
            }
        });
        CampoVenderQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoVenderQuantidadeKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("CÓDIGO DE BARRAS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("QUANTIDADE");

        botaovender.setText("VENDER");
        botaovender.setEnabled(false);
        botaovender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaovenderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("VALOR TOTAL: ");

        textoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoValor.setText("0");

        CampoCliente.setEnabled(false);
        CampoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoClienteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("CLIENTE");

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaovender, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoValor))
                            .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CampoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CodigoBarrasVender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CampoVenderQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoBarrasVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoVenderQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaovender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(painel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ESTOQUE/VENDA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ALTERAR");

        textoEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoEditar.setForeground(new java.awt.Color(255, 0, 0));
        textoEditar.setText("Sem permissão para alterar o estoque");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("(Altere direto na tabela)");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(textoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomePessoa))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(textoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(painelPrincipal);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("GERENCIAR");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ALTERAR NOME");

        campoAlteradorNome.setEnabled(false);

        botaoAlteradorNome.setText("ALTERAR");
        botaoAlteradorNome.setEnabled(false);
        botaoAlteradorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlteradorNomeActionPerformed(evt);
            }
        });

        botaocliente.setText("VERIFICAR ULTIMO CLIENTE");
        botaocliente.setEnabled(false);
        botaocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoAlteradorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAlteradorNome))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaocliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(botaocliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(campoAlteradorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlteradorNome))
                .addGap(0, 165, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoBarrasVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoBarrasVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoBarrasVenderActionPerformed

    private void botaoAlteradorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlteradorNomeActionPerformed
        gerente.funcao(campoAlteradorNome.getText());
        eGerente(gerente);
    }//GEN-LAST:event_botaoAlteradorNomeActionPerformed
    public int aux = 0;
    private void tabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDadosMouseClicked
        //COLOCA OS VALORES NOS CAMPOS DE VEMDA
        int permission = 0;
        if (!textoEditar.getText().equals("Sem permissão para alterar o estoque")) {
            permission = gerente.getPrivilégio();
        }
        //SETA O CAMPO CHAVE COM O ID DA LINHA SELECIONADA
        CodigoBarrasVender.setText(tabela.getValueAt(tabelaDados.getSelectedRow(), 0).toString());
        //EXIBE UMA MENSAGEM PARA QUE A TABELA NÃO POSSA SER EDITADA
        if (permission == 0) {
            JOptionPane.showMessageDialog(null, "Linha selecionada!");
        }
    }//GEN-LAST:event_tabelaDadosMouseClicked

    private void CampoVenderQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoVenderQuantidadeActionPerformed

    }//GEN-LAST:event_CampoVenderQuantidadeActionPerformed

    private void CampoVenderQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoVenderQuantidadeKeyTyped
       //HABILITA OU NÃO O BOTÃO DE VENDER
        char c = evt.getKeyChar();
        //VARIAVEL COM O´PREÇO DO ITEM
        double total = Double.parseDouble(tabela.getValueAt(tabelaDados.getSelectedRow(), 3).toString());
        //VERIFICA SE É UM NUMERO DIGITADO NO CAMPO DE QUANTIDADE
        
        if (!Character.isDigit(c)) {
            evt.consume();
            //VERIFICA SE A QUANTIDADE DIGITADA E MENOR QUE A QUANTIDADE DISPONIVEL
            if (Integer.parseInt(CampoVenderQuantidade.getText()) <= Integer.parseInt(tabela.getValueAt(tabelaDados.getSelectedRow(), 2).toString())) {
                botaovender.setEnabled(true);
                total = total * Integer.parseInt(CampoVenderQuantidade.getText());
                //FORMATANDO O NÚMERO
                DecimalFormat format = new DecimalFormat("0.0#");
                textoValor.setText("R$ "+String.valueOf(format.format(total)));
            } else {
                botaovender.setEnabled(false);
            }
        }
    }//GEN-LAST:event_CampoVenderQuantidadeKeyTyped

    private void botaovenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaovenderActionPerformed
        int menos = Integer.parseInt(tabela.getValueAt(tabelaDados.getSelectedRow(), 2).toString()) - Integer.parseInt(CampoVenderQuantidade.getText());
        if (menos >= 0) {
            tabelaDados.setValueAt(menos,tabelaDados.getSelectedRow(),2);
            if (CampoCliente.isEnabled()) {
                funcionario.funcao(CampoCliente.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERRO 12 - QUANTIDADE INVÁLIDA");
        }
    }//GEN-LAST:event_botaovenderActionPerformed

    private void CampoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoClienteActionPerformed

    private void botaoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoclienteActionPerformed
        JOptionPane.showMessageDialog(null, "O seu ultimo cliente foi: "+funcionario.getcliente());
    }//GEN-LAST:event_botaoclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCliente;
    private javax.swing.JTextField CampoVenderQuantidade;
    private javax.swing.JTextField CodigoBarrasVender;
    private javax.swing.JLabel NomePessoa;
    private javax.swing.JButton botaoAlteradorNome;
    private javax.swing.JButton botaocliente;
    private javax.swing.JButton botaovender;
    private javax.swing.JTextField campoAlteradorNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JLabel textoEditar;
    private javax.swing.JLabel textoValor;
    // End of variables declaration//GEN-END:variables
}
